stages:
  - test
  - publish

.test-opensource: &test-opensource
  stage: test
  tags:
    - docker
  image: centos:7
  before_script:
    - curl -s https://packagecloud.io/install/repositories/tarantool/$TARANTOOL_REPO/script.rpm.sh | bash
    - yum -y install git gcc cmake tarantool tarantool-devel
    - tarantool -V
    - tarantoolctl rocks install luatest 0.3.0
    - tarantoolctl rocks install luacheck 0.25.0
  script:
    - tarantoolctl rocks make
    - make test -C build.luarocks ARGS="-V"

test-opensource-1.10:
  <<: *test-opensource
  variables:
    TARANTOOL_REPO: "1_10"

test-opensource-2.2:
  <<: *test-opensource
  variables:
    TARANTOOL_REPO: "2_2"

test-opensource-2.x:
  <<: *test-opensource
  variables:
    TARANTOOL_REPO: "2_3"

publish-scm-1:
  stage: publish
  tags:
    - docker
  image: centos:7
  only:
    - master
  script:
    - >
      curl -X PUT -F "rockspec=@ddl-scm-1.rockspec"
      https://${ROCKS_USERNAME}:${ROCKS_PASSWORD}@${ROCKS_SERVER}

publish-release:
  stage: publish
  tags:
    - docker
  image: centos:7
  only:
    - tags
  script:
    - >
      sed
      -e "s/branch = '.\+'/tag = '${CI_COMMIT_TAG}'/g"
      -e "s/version = '.\+'/version = '${CI_COMMIT_TAG}-1'/g"
      ddl-scm-1.rockspec > ddl-${CI_COMMIT_TAG}-1.rockspec
    - >
      curl -X PUT -F "rockspec=@ddl-${CI_COMMIT_TAG}-1.rockspec"
      https://${ROCKS_USERNAME}:${ROCKS_PASSWORD}@${ROCKS_SERVER}
