name: Publish

on:
  push:
    branches: [master]
    tags: ['*']

jobs:
  version-check:
    # We need this job to run only on push with tag.
    if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') }}
    runs-on: ubuntu-20.04
    steps:
      - name: Check module version
        uses: tarantool/actions/check-module-version@master
        with:
          module-name: 'ddl'

  publish-scm-1:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: tarantool/rocks.tarantool.org/github-action@master
        with:
          auth: ${{ secrets.ROCKS_AUTH }}
          files: ddl-scm-1.rockspec

  publish-tag:
    if: startsWith(github.ref, 'refs/tags/')
    needs: version-check
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: tarantool/setup-tarantool@v2
        with:
          tarantool-version: '2.11'

      - name: Prepare apt repo
        run: curl -L https://tarantool.io/release/2/installer.sh | bash

      - name: Install tt cli
        run: sudo apt install -y tt
        env:
          DEBIAN_FRONTEND: noninteractive

      # Make a release
      - run: echo TAG=${GITHUB_REF##*/} >> $GITHUB_ENV
      - run: tt rocks new_version --tag ${{ env.TAG }}
      - run: tt rocks install ddl-${{ env.TAG }}-1.rockspec
      - run: tt rocks pack ddl ${{ env.TAG }}

      - uses: tarantool/rocks.tarantool.org/github-action@master
        with:
          auth: ${{ secrets.ROCKS_AUTH }}
          files: |
            ddl-${{ env.TAG }}-1.rockspec
            ddl-${{ env.TAG }}-1.all.rock
